<div style="text-align: right">INFO 6105 Data Science Eng Methods and Tools, Spring 19 midterm</div>
<div style="text-align: right">Dino Konstantopoulos, 13 March 2019</div>
<div style="text-align: right">100 points total</div>

# INFO 6105 Spring 19 Midterm

You have up to an hour and a half. Good luck.

<div style="text-align: right">15 points</div>

## 1. Hurricanes

Read hurricanes data from `hurricanes.csv` into a `pandas` data frame. Find the average number of hurricanes per quarter for years nineteen-fifty to nineteen-fiftynine, which includes years nineteen-fifty as well as nineteen-fiftynine, and where first quarter is months of January, February, and March, second quarter is months of April, May, and June, third quarter is months of July, August, and September, and fourth quarter is months of October, November, and December, and tabulate them below.

Also, plot the number of hurricanes per quarter.

</br >
<center>
<img src="ipynb.images/hurricanes.jpg" width=400 />
</center>

In [15]:
%matplotlib inline
import  matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [16]:
tables = pd.read_csv("data/hurricanes.csv")
tables.head()

year     month  passengers
0  1949   January         112
1  1949  February         118
2  1949     March         132
3  1949     April         129
4  1949       May         121

In [3]:
newtable = tables[tables.year == 1950]
quarter1 = newtable[0:3].passengers.sum()
quarter2 = newtable[3:6].passengers.sum()
quarter3 = newtable[6:9].passengers.sum()
quarter4 = newtable[9:12].passengers.sum()

In [4]:
data = {'Quarter':['quarter1','quarter2','quarter3','quarter4'],
     'Passengers':[quarter1,quarter2,quarter3,quarter4]}
result = pd.DataFrame(data)
result

Quarter  Passengers
0  quarter1         382
1  quarter2         409
2  quarter3         498
3  quarter4         387

<div style="text-align: right">15 points</div>

# 2. Divisible numbers

How many numbers between zero and a thousand, when you take the square of each number and then add the number 1, can be divided exactly by seventeen (with 0 remainder)? 

</br >
<center>
<img src="ipynb.images/divisible.png" width=150 />
</center>

You need to write your own functions, and if you want to use python functions, you can only use these: `map()`, `filter()`, and `reduce()`.

In [5]:
from collections import Counter
from functools import reduce

def getResult(n):
    result = []
    for n in range(n):
        if (n*n + 1)%17 == 0: 
            result.append(n)
    return result
            
result = getResult(100)
print(result)

[4, 13, 21, 30, 38, 47, 55, 64, 72, 81, 89, 98]


<div style="text-align: right">20 points</div>

# 3. DNA

If you have a DNA sequence like the one in the cell underneath, write a four by four stochastic transition matrix $M(n,m)$ where each of its elements represents the following probability:

* DNA base with index m appears right after DNA base with index n

A DNA base is either `adenine`, denoted by the letter `a`, `cytosine`, denoted by the letter `c`, `thymine`, denoted by the letter `t`, and `guanine`, denoted by the letter `g`.

</br >
<center>
<img src="ipynb.images/dnastructure.jpg" width=300 />
</center>

Don't forget to verify that the sum over each row of matrix elements adds up to 1.

Using the stochastic transition matrix, determine how these bases are distributed in the steady-state limit. In other words, the vector $z$ such that `A @ z = z`.

Finding the steady state of DNA is a first approximation in the map of the future of humankind :-)

In [9]:
dna = '''cccaacatacagtgaactcggacacgcctgctcactgtgaaccctgcacttgtcgccgccggctatgcaagagattctag
gagagggtacccggaccagacataccgaaagaacaacacccccgcctctccgtcgctcacccacatgtaattcgtaccgg
tggtggtacacctcgcaccgcaccagcgcctcaaccgtcccaaaaacccccacccctcggccaagtccataagggaggcg
caaagacagcccatccccccgaagagcattccctaacgacgccggcccaagagacccggcactactgacgtccacggtac
ctccgccaaaccccccgggggccttcagatcgccctagcccgaagcaaacacctcctcccccgctcacgcctccacaag'''
dna = dna.replace('\n', '')
dna = list(dna)
len(dna)

399

In [10]:
dna.index('t')

7

In [11]:
mylist = []
for i in range(0, 400):
    i = dna.index('t')
    mylist.append(i)
    dna = dna[i:]

In [22]:
import numpy as np

t = [i  for i, x in enumerate(dna) if x == 't']
c = [i  for i, x in enumerate(dna) if x == 'c']
g = [i  for i, x in enumerate(dna) if x == 'g']
a = [i  for i, x in enumerate(dna) if x == 'a']

c_c = len([x for x in c if x+1 in c]) / len(c)
c_t = len([x for x in c if x+1 in t]) / len(c)
c_g = len([x for x in c if x+1 in g]) / len(c)
c_a = len([x for x in c if x+1 in a]) / len(c)

# t = matrix([[c_c, c_t, c_g, c_a], [...], [...], [...]])

m = np.zeros([4,4])
bases = [c, t, g, a]
for i in range(0,4):
    for j in range(0,4):
        m[i,j] = len([x for x in bases[i] if x+1 in bases[j]]) / len(bases[i])
print(m)

[[0.4375     0.15       0.19375    0.21875   ]
 [0.45283019 0.09433962 0.20754717 0.24528302]
 [0.33333333 0.16666667 0.23809524 0.25      ]
 [0.4        0.09473684 0.23157895 0.27368421]]


In [21]:
np.linalg.eig(m)

(array([ 0.99744221,  0.08142787, -0.04230441,  0.0070534 ]),
 array([[ 0.50164552,  0.54944843, -0.17448096, -0.04758608],
        [ 0.50155709,  0.22962591,  0.65052895,  0.10543861],
        [ 0.49537003, -0.64137611, -0.58364527, -0.73287604],
        [ 0.50139883, -0.48375102,  0.45357102,  0.6704558 ]]))

In [3]:
matrix = np.arange(16).reshape(4, 4)
matrix

NameError: name 'np' is not defined

In [4]:
theta = np.deg2rad(45)
theta

NameError: name 'np' is not defined

<div style="text-align: right">20 points</div>

# 4. Mountain transformations

</br >
<center>
<img src="ipynb.images/rockclimbing.jpg" width=400 />
</center>

Determine the transformation matrix that rotates unit perpendicular vectors (n, m) in the (x, y) plane by thirty degrees in a counterclockwise directions and expands n by three while contracting m by half. 

Find its inverse, as well, in a way that underscores that you understand the effects of this matrix. 

</br >
<center>
<img src="ipynb.images/base-rotation.png" width=400 />
</center>

In [23]:
A @ x = y
a11 * x1 + a12 * x2 = y1
a21 * x1 + a22 * x2 = y2
a12 = a21
a11 = a22

SyntaxError: can't assign to operator (<ipython-input-23-b0cb8a0249d6>, line 1)

<div style="text-align: right">30 points</div>

# 5. Airports

</br >
<center>
<img src="ipynb.images/airports.gif" width=400 />
</center>

Order airports from busiest to least-busiest using files `airports.csv` and `ontime.csv`.

Google's PageRank algorithm unleashes a silver surfer on a graph whose nodes represent the states of the state machine represented by silver surfer locations, and finds the steady state regime of the Markovian silver surfer chain by solving a linear system of equations either analytically using sparse matrix methods, or approximately using the power method which leverages knowledge of the dominant eigenvector.

PageRank makes the assumption that each and every location on the graph can be reached from any other location, but that is often not the case when the out degree of a location is 0. So we allow for the possibility for any graph location to have a small probability to transit to another location (shrimp eating sharks, remember?). This is represented by Google's damping factor in what I've called the silver surfer equation.

Use pandas' `read_csv()` to read in the csv files, use `networkx` to represent the airports graph, compute out degrees the way we did it in class with food networks, and then either solve directly (if you can) or use an iterative method to order airports from busiest to least-busiest.
Plot the airports graph using `networkx`' `draw()` function.

In [9]:
import networkx as nx
import scipy.linalg as la
airports = pd.read_csv("data/airports.csv")
airports.head()

id ident           type                                name  \
0    6523   00A       heliport                   Total Rf Heliport   
1  323361  00AA  small_airport                Aero B Ranch Airport   
2    6524  00AK  small_airport                        Lowell Field   
3    6525  00AL  small_airport                        Epps Airpark   
4    6526  00AR         closed  Newport Hospital & Clinic Heliport   

   latitude_deg  longitude_deg  elevation_ft continent iso_country iso_region  \
0     40.070801     -74.933601          11.0       NaN          US      US-PA   
1     38.704022    -101.473911        3435.0       NaN          US      US-KS   
2     59.949200    -151.695999         450.0       NaN          US      US-AK   
3     34.864799     -86.770302         820.0       NaN          US      US-AL   
4     35.608700     -91.254898         237.0       NaN          US      US-AR   

   municipality scheduled_service gps_code iata_code local_code home_link  \
0      Bensalem                no      00A       NaN        00A       NaN   
1         Leoti                no     00AA       NaN       00AA       NaN   
2  Anchor Point                no     00AK       NaN       00AK       NaN   
3       Harvest                no     00AL       NaN       00AL       NaN   
4       Newport                no      NaN       NaN        NaN       NaN   

  wikipedia_link keywords  
0            NaN      NaN  
1            NaN      NaN  
2            NaN      NaN  
3            NaN      NaN  
4            NaN     00AR

In [10]:
ontime = pd.read_csv("data/ontime.csv")
ontime.head()

ORIGIN_AIRPORT_ID  ORIGIN_AIRPORT_SEQ_ID  ORIGIN_CITY_MARKET_ID  \
0              10135                1013505                  30135   
1              10135                1013505                  30135   
2              10135                1013505                  30135   
3              10135                1013505                  30135   
4              10135                1013505                  30135   

   DEST_AIRPORT_ID  DEST_AIRPORT_SEQ_ID  DEST_CITY_MARKET_ID  Unnamed: 6  
0            10397              1039707                30397         NaN  
1            10397              1039707                30397         NaN  
2            10397              1039707                30397         NaN  
3            10397              1039707                30397         NaN  
4            10397              1039707                30397         NaN

In [11]:
import networkx as nx

In [14]:
column_edge = 'id'
column_ID = 'name'
g = nx.Graph()
g.clear() 
for m in airports.name:
    g.add_node(m)